name: Build Assets

on:
  pull_request:
    branches: [2.x]
    types: [closed]
    
jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: 2.x

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: 2.x
          commit_message: >
            Chore: build assets
